name: 'Setup Static PHP Action'
description: 'GitHub Actions for setting up a static PHP action'
author: 'crazywhalecc'

# Define your inputs here.
inputs:
  php-version:
    description: 'Setup PHP Version'
    required: false
    default: '8.2'
  extensions:
    description: 'PHP Extensions'
    required: false
    default: '待确定'
  ini-values:
    description: 'PHP INI Values'
    required: false
    default: '待确定'
  libraries:
    description: 'Additional PHP Libraries'
    required: false
    default: '待确定'
  enable-zts:
    description: 'Enable ZTS'
    required: false
    default: 'false'
  sapi:
    description: 'PHP SAPI'
    required: true
    default: 'cli'

# Define your outputs here.
outputs:
  sapi:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
